#!/bin/bash

# Check if venv exists, and create it if it doesn't
if [ ! -d ".venv" ]; then
  echo "Virtual environment not found. Creating venv..."
  python3 -m venv .venv
fi

# Activate the virtual environment
echo "Activating the virtual environment..."
source ./.venv/scripts/activate

# Install the dependencies from requirements.txt
echo "Installing dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo "Dependencies installed successfully."


git pull request origin main
cd freakyapp
python manage.py makemigrations
python manage.py migrate
python manage.py runserver

echo "Server Running"

