# Generated by Django 5.1.3 on 2024-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education'), ('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education'), ('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education')], max_length=100),
        ),
    ]
