# Generated by Django 5.1.3 on 2024-11-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(choices=[('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education')], default='NO', max_length=50),
        ),
    ]
