# Generated by Django 5.1.3 on 2024-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='topic',
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.CharField(choices=[('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education')], default='NO', max_length=200, verbose_name='Event Topic'),
        ),
    ]
