# Generated by Django 5.1.3 on 2024-11-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_event_topic_event_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tech', 'Technology'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='topics',
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='events', to='home.topic'),
        ),
    ]
